export type AppPage = {
    url: string;
    icon?: string;
    title: string;
    page?: React.ComponentType<any>;
    routeOnly?: boolean;
    exact?: boolean;
    // allowedRoles?: RoleValues[];
    tableParentName?: string;
    // tableMetadata?: ColumnMetadata[];
    selectQuery?: string;
    // filterQuery?: Filter[];
    // sortingQuery?: SortingState;
    searchColumn?: string[];
    nameContent?: Array<string>;
    children?: AppPage[];
    toggleOnly?: boolean;
    lookerUrl?: string;
    lookerUrlMobile?: string | null;
    // onRowClicked?: (data: Row<any>) => void;
    globalFilterColumn?: Array<string>;
    platform?: ('desktop' | 'mobile')[];
};